version: 2

project_name: node-cleaner

builds:
  - skip: true  # Skip builds since we're building manually with Rust

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - dist/bin/*
      - README.md
      - LICENSE*

release:
  draft: false
  prerelease: false
  name_template: "Release {{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
