[package]
name = "node-cleaner"
version = "0.1.1"
edition = "2025"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap-verbosity-flag = "3.0.2"
env_logger = "0.11.8"
glob = "0.3.2"
log = "0.4.27"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
walkdir = "2.5.0"
