name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    name: Build and Release Linux Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build binary
        run: cargo build --release

      - name: Upload release binary
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/node-cleaner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
